### ISSUE TITLE
关于自定义参数里带有://时无法正常匹配

### ISSUE THREAD

**Issue by dalianmengwei** [mogujie/MGJRouter#11]
形如这种时无法正常匹配 
[MGJRouter openURL:@"mgj://search/bicycle?color=://"];

实际需求，传递头像或者图片作为参数
 [MGJRouter openURL:@"mgj://search/bicycle?color=http://wx.qlogo.cn/mmopen/93g7vLJ3bPCwj4xtcD8JfXyjdxh2vGp6ObnmEiaYrjXBpBI9MUuUZEZdn9eM6ILia5utSuoNCE0IicvAXia7DBNnXUiakcrGha03j/0"];

我不清楚如果参数里面包含“://”或者“/://”这类的是否也会有问题

**Comment by lzyy** [comment]
这个最好通过 URLEncode 转一下

**Comment by dalianmengwei** [comment]
我也考虑过用 URLEncode 转义，也试过在generateURLWithPattern方法里面对全部参数统一进行转义。
还有一个问题是，如果转义的话，那用到参数的时候还要进行反转义，这样会不会不方便？是否有别的更好的思路？

**Comment by lzyy** [comment]
把这个 URL 当作正常的 URL 处理即可。正常的 URL 在到达服务端时都需要 encode。

至于麻烦的话，提供一个公共的方法或者在某个入口统一处理应该就可以了。
