### ISSUE TITLE
当主URL内部参数有URL链接是会出现问题

### ISSUE THREAD

**Issue by colinlovefish** [mogujie/MGJRouter#13]
将- (NSArray*)pathComponentsFromURL:(NSString*)URL方法内部的一个判断
pathSegments.count == 2 改为pathSegments.count >= 2 解决，如果这样改有后遗症，还请告知

**Comment by lzyy** [comment]
嗯，确实如此

**Comment by zeqinjie** [comment]
请问URL内部参数有Url怎么处理呢？如mgj://detail?url=http://www.baidu.com&age=19 因为url的参数带有://。

**Comment by Nododo** [comment]
> 请问URL内部参数有Url怎么处理呢？如mgj://detail?url=http://www.baidu.com&age=19 因为url的参数带有://。

我也遇到这个问题了  只能另外封装一层  单独处理这种情况

**Comment by JpacheGitHub** [comment]
在
```
- (NSArray*)pathComponentsFromURL:(NSString*)URL {
}
```
这个方法里, 刚一进方法的时候添加代码
```
- (NSArray*)pathComponentsFromURL:(NSString*)URL {
    NSURL *tempURL = [NSURL URLWithString:URL];
    if (tempURL.query.length) {
        URL = [URL substringToIndex:URL.length - tempURL.query.length - 1];
    }
}
```
最后的 - 1 不加也可以, 没影响, 不加 - 1 就不用加长度判断保护了
就可以了, 封装一层没必要 @Nododo @zeqinjie @lzyy @colinlovefish
