### ISSUE TITLE
关于首页tabbar 之间的切换

### ISSUE THREAD

**Issue by ivanyang1984** [mogujie/MGJRouter#2]
如果我首页 也像 蘑菇街那样 有5个 tab item  我在这些item之间来回切换  我可以调 导航的方法吗？
例如 我在首页推了很多VC 盖在上面   我在点右上角的 聊聊聊 这个时候 推出了一个 新的聊聊聊界面， 但是我希望 这种是 回到tabbar  那个选中的 聊聊聊  要怎么做？

**Comment by Blankdlh** [comment]
@ivanyang1984 可以用不同的 URL 做区分。

**Comment by yuhanle** [comment]
这个我是这样做的

首先vc有一个基类，基类生命一个block，在基类的viewDidAppear方法里判断首次加载这个页面的时候，如果这个block存在，就调用。

接下来是比较重要的部分了。
当前页面设为A，要去的页面设为B，返回的页面C
1.首先按照你想的方式跳到你的新页面B
2.在生成B页面的时候，给B设置一个block
3.这时候页面B会正常的显示出来，在出现以后就会执行你传的block
4.这个block里的操作，其实就是对导航栈的重新设置。
   这里完全可以按照url来判断，在B页面点击返回页面C，设置好vcs以后就达到你想要的效果了~
