### ISSUE TITLE
有个BUG出现

### ISSUE THREAD

**Issue by huangzhentong** [mogujie/MGJRouter#7]
函数1
 [MGJRouter registerURLPattern:@"mgj://search/:query" toHandler:^(NSDictionary *routerParameters) {
        [self appendLog:@"匹配到了 url，以下是相关信息"];
        [self appendLog:[NSString stringWithFormat:@"routerParameters:%@", routerParameters]];
    }];

```
[MGJRouter openURL:@"mgj://search/bicycle?color=red"];
```

函数 2
# define TEMPLATE_URL @"mgj://search/:keyword"

[MGJRouter registerURLPattern:TEMPLATE_URL  toHandler:^(NSDictionary *routerParameters) {
    NSLog(@"routerParameters[keyword]:%@", routerParameters[@"keyword"]); // Hangzhou
}];

[MGJRouter openURL:[MGJRouter generateURLWithPattern:TEMPLATE_URL parameters:@[@"Hangzhou"]]];

选调用 函数1 再调用函数2，再次调用函数1 的时候结果跑到函数2的handler里面

**Comment by lzyy** [comment]
因为这两个 url `mgj://search/:query` 和 `mgj://search/:keyword` 其实是一样的，所以后面那个覆盖了前面那个。
