### ISSUE TITLE
ModuleManager  registerProtocol 

### ISSUE THREAD

**Issue by lsm307742191** [mogujie/MGJRouter#8]
这个模块没有开源吗？什么时候开源呢？

**Comment by lzyy** [comment]
这个模块挺简单的，它主要做两件事，提供一个协议，包含了 onInit 方法，只要实现了这个方法，就会在初始化时被调用；还有就是 foward appdelegate 的一些方法。

**Comment by lsm307742191** [comment]
期望还是能够体验下作者的版本

**Comment by calvingit** [comment]
虽然没看懂说什么东东，我猜是为了减轻Appdelegate的东西吧，参考一下豆瓣最近开源的这个[FRDModuleManager](https://github.com/lincode/FRDModuleManager)

**Comment by lzyy** [comment]
嗯，跟豆瓣的这个非常像···
